### ISSUE TITLE
javascript + oauth2 or openid

### ISSUE THREAD

**Issue by nmocruz** [microsoft/azure-devops-auth-samples#16]
Theres any way to setup oauth in a spa but without adal, just with any js library for oauth2 or openid connect?

if yes, there's any sample?

**Comment by nmocruz** [comment]
I was able to do it with oidc-client-js, but because of CORS issues on some endpoints like signinkeys, I had to feed manually some information from the metada endpoint. https://github.com/IdentityModel/oidc-client-js/issues/413

should be good to have a full sample using openid connect and an how to setup all like we have with adal.js.

**Comment by anydot** [comment]
closing due to old age
