### ISSUE TITLE
NonInteractivePatGenerationSample AcquireTokenAsync() AdalServiceException: AADSTS70002

### ISSUE THREAD

**Issue by yiqzhou** [microsoft/azure-devops-auth-samples#20]
I have a web app using AAD that allows us login with microsoft account. In Program.cs I replaced the $username and $password with that of my account and replaced $aadApplicationId with id at here:

![image](https://user-images.githubusercontent.com/29744299/41102498-9df3ba8e-6a99-11e8-8862-505c2e27bea9.png)

  Yet when the program runs to this line

    var result = authenticationContext.AcquireTokenAsync(VstsResourceId, aadApplicationID, adalCredential).Result;

an exception is thrown:
AdalServiceException: AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion'. Trace ID: 6ff59af0-9185-4f64-a5f4-fc1331c30300 Correlation ID: d8914c45-f234-4b3e-913c-dc7bfe647374 Timestamp: 2018-06-07 13:12:59Z

**Comment by jffaust** [comment]
I'm getting the same error when running the ManagedClientConsoleAppSample
![image](https://user-images.githubusercontent.com/4367222/87950402-42dd3880-ca75-11ea-9d0e-a7caf38a0841.png)

**Comment by jffaust** [comment]
I was able to make it work by updating the Redirect URI from Web to Mobile/Desktop based on the comment [here](https://github.com/Azure-Samples/active-directory-dotnetcore-devicecodeflow-v2/issues/9#issuecomment-547553013).

**Comment by anydot** [comment]
Closing as the examples were updated to use MSAL
