### ISSUE TITLE
You are not authorized to access our service

### ISSUE THREAD

**Issue by vyaspentakota** [microsoft/azure-devops-auth-samples#35]
Hi,

I downloaded and followed the instructions and when I tried running am getting the below error.

Microsoft.VisualStudio.Services.Client.Controls.BrowserFlowException: 'SP324091: You are not authorized to access our service.'

file : azure-devops-auth-samples-master\ClientLibraryConsoleAppSample\Program.cs

**Comment by anydot** [comment]
The account you used likely didn't have permission to access your test organization
