### ISSUE TITLE
OAuthWebSample -  The resource cannot be found  /oauth/requesttoken

### ISSUE THREAD

**Issue by tgogoi** [microsoft/azure-devops-auth-samples#36]
Steps:
 1. Take the latest Sample code 
 2.  Update OAuthWebSample config file with correct app Id, secrets etc after registering app
 3. Run OAuthWebSample on Visual studio IIS express
 4. Click on "Authorize" button on the home page ( to get the token )

Result: Browser fails to get resource 
/oauth/requesttoken

****Server Error in '/' Application.
The resource cannot be found.
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

Requested URL: /oauth/requesttoken

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.3282.0****

**Comment by tgogoi** [comment]
Workaround is to replace /oauth/requesttoken with /oauth/authorize in the index.html

**Comment by admachiano** [comment]
I can't find the index.html button in the OAuthWebSample solution?  I'm a total noob and am stuck on this.

**Comment by anydot** [comment]
Will be fixed in PR #59
