### ISSUE TITLE
CORS error when fetching projects with JavaScriptWebAppSample

### ISSUE THREAD

**Issue by tamasfoldi** [microsoft/azure-devops-auth-samples#84]
Hi!

I've configured my app based on the readme, but I'm getting this error (I have replaced the TENANT_NAME to my tenant): 
```
Access to fetch at 'https://dev.azure.com/{TENANT_NAME}/_apis/projects?api-version=4.0' from origin 'http://localhost:8081' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Could anyone help me how they solved this issue? Where should I enable the localhost origin?

Regards,
Tamas

**Comment by tamasfoldi** [comment]
It was my fault. My AAD was not connected to azure dev ops

**Comment by pjirsa** [comment]
My org IS connected to AAD and I'm still getting this error. Was there anything else you did to resolve the issue?
