### ISSUE TITLE
timeouts - Unable to Acquire Token - AngularCLI

### ISSUE THREAD

**Issue by DigitalKrony** [microsoft/azure-devops-auth-samples#9]
Only getting timeouts when I get to the `acquireToken` function. Not only in my own code but also when trying to utilize this example code.

Where am I getting the VSTS Resource ID from? I'm not seeing a clear mapping on where I'm getting this value from AAD. 

My AAD login works as expected however, I have zero access to VSTS.

**Comment by justmarks** [comment]
@DigitalKrony are you still having issue? I'm happy to help but wanted to make sure this is still active since it's 5 months old.

**Comment by DigitalKrony** [comment]
Sadly I've still been unable to aquire a token from VSO. Luckily, this part of the project isn't pressing (yet) and I've been able to push it back. However, as time goes on I'll end up back in this chunk of code.

**Comment by justmarks** [comment]
@DigitalKrony can you reach out to me via email (jmarks@microsoft.com) and share the code you're using. Happy to help debug.

**Comment by anydot** [comment]
closing due to old age
